In [2]:
import numpy as np

In [3]:
arr_1 = np.array([1, 2, 3, 4, 5, 6]) #-> 1-D Array
print("1-D Array-\n", arr_1)

arr_2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) #-> 2-D Array
print("2-D Array-\n", arr_2)

1-D Array-
 [1 2 3 4 5 6]
2-D Array-
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(type(arr)) # return type 
print(arr.size) # return size/no. of elements in an array
print(arr.shape) # return (rows, columns) no of rows and columns 
print(arr.dtype) # return dtype mainly int64 or int32 on windows
print(arr.ndim) # return dimension of array like, 2 -> 2D array

<class 'numpy.ndarray'>
6
(2, 3)
int64
2


In [10]:
##NumPy arrays are strongly typed, meaning all elements share the same data type.

arr = np.zeros((4,3)) #4X3 array of zero(0)
print(arr, "\n")

arr = np.ones((4,3)) #4X3 array of one(1)
print(arr, "\n")

arr = np.eye((6)) #Identity matrix of 6X6
print(arr, "\n")

arr = np.full((2,3), 7) #2X3 array filled with 7
print(arr, "\n")

arr = np.arange(1, 50, 3) #return array like [1, 1+3, 1+3+3, 1+3+3....... <50]
print(arr, "\n")

arr = np.arange(100, 1, -2)
print(arr, "\n")

arr = np.linspace(1, 100, 7) #return 7 element in array which are equally distributed between 1 and 100
print(arr, "\n")



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]] 

[[7 7 7]
 [7 7 7]] 

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49] 

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2] 

[  1.   17.5  34.   50.5  67.   83.5 100. ] 



In [16]:
###Changing Data Types
arr_2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]], dtype = 'float64')
print(arr_2)
print(arr_2.dtype)

n = arr_2.astype('int64')
print(n, n.dtype)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64
[[1 2 3]
 [4 5 6]
 [7 8 9]] int64


In [21]:
###Reshaping and Flattening Arrays
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9], [13, 14, 15]])
print(arr, "\n")
reshaped = arr.reshape(3, 4)
print(reshaped, "\n")
reshaped = arr.reshape(2, 6)
print(reshaped, "\n")
reshaped = arr.reshape(1, 12)
print(reshaped, "\n")
reshaped = arr.reshape(12, 1)
print(reshaped, "\n")
reshaped = arr.reshape(4, 3)
print(reshaped, "\n")

flattened = arr.flatten() #2D->1D
print(flattened)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [13 14 15]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 13 14 15]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 13 14 15]] 

[[ 1  2  3  4  5  6  7  8  9 13 14 15]] 

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [13]
 [14]
 [15]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [13 14 15]] 

[ 1  2  3  4  5  6  7  8  9 13 14 15]
