In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9], [13, 14, 15]])

In [24]:
flat = arr.flatten()

In [25]:
print(flat)
print(flat[1])

[ 1  2  3  4  5  6  7  8  9 13 14 15]
2


In [7]:
print(flat[4])

5


In [8]:
print(flat[1:6])

[2 3 4 5 6]


In [9]:
print(flat[5:])

[ 6  7  8  9 13 14 15]


In [10]:
print(flat[5:len(flat)])

[ 6  7  8  9 13 14 15]


In [11]:
print(flat[:5])

[1 2 3 4 5]


In [12]:
print(flat[::3])

[ 1  4  7 13]


# Slicing returns a view, not a copy! Changes affect the original array.
This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array.
Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

Why does this happen?
- Memory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.
- Performance: Enables faster access and manipulation of large datasets without duplicating data.


In [26]:
print(flat)

a = flat[3:9]
print(a)

a[0] = 4545

print(a)
print(flat)

[ 1  2  3  4  5  6  7  8  9 13 14 15]
[4 5 6 7 8 9]
[4545    5    6    7    8    9]
[   1    2    3 4545    5    6    7    8    9   13   14   15]


In [28]:
'''To should use copy() function for this.'''

a = flat[4: 8].copy()
print(a)
a[0] = 545454
print(a)
print(flat)

[5 6 7 8]
[545454      6      7      8]
[   1    2    3 4545    5    6    7    8    9   13   14   15]


In [32]:
"""Fancy Indexing"""
arr = np.array([28, 54, 4, 18, 7, 87, 66, 21, 72, 13])
index = [0, 2, 3]
print(arr[index])

print(arr[[5, 0, 3]])

[28  4 18]
[87 28 18]


In [37]:
'''Boolean Masking / Filter Data'''
arr = np.array([28, 54, 4, 18, 7, 87, 66, 21, 72, 13])
Mask = (arr>25)
print(Mask)
print(arr[Mask])

print(arr[arr>25])

[ True  True False False False  True  True False  True False]
[28 54 87 66 72]
[28 54 87 66 72]
