# Understanding Axes in NumPy
Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:
- 1D array → 1 axis (axis 0)
- 2D array → 2 axes (axis 0 = rows, axis 1 = columns)
- 3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)


In [1]:
import numpy as np

In [7]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#Axis 0 (rows) → Operations move down the columns.
#Axis 1 (columns) → Operations move across the rows.
print("sum_for_axis_0 = ", np.sum(arr, axis=0))
print("sum_for_axis_1 = ", np.sum(arr, axis=1))

sum_for_axis_0 =  [12 15 18]
sum_for_axis_1 =  [ 6 15 24]


In [13]:
#Indexing in Multidimensional Arrays

print(arr[0,1])
print(arr[0:2, 1:3])

2
[[2 3]
 [5 6]]


In [24]:
arr3D = np.array([[[1, 2, 3], 
                   [4, 5, 6]],
                  [[7, 8, 9], 
                   [10, 11, 12]]])
print(arr3D[0, 1, 0])
print(arr3D[1, 0, 2])

print(arr3D[:, 1, :])
print(arr3D[:, :, 2])
print(arr3D[:, 1, 2])
first_row_of_first_arr = arr3D[0,0,:]
print("first_row_of_fisrst_arr = ", first_row_of_first_arr)
first_row = arr3D[:, 0, :]
print("first_row = ", first_row)

4
9
[[ 4  5  6]
 [10 11 12]]
[[ 3  6]
 [ 9 12]]
[ 6 12]
first_row_of_fisrst_arr =  [1 2 3]
first_row =  [[1 2 3]
 [7 8 9]]


In [28]:
#  Changing Data Along an Axis
arr3D[0, 0, :] = 0
print(arr3D, "\n\n")

arr3D[0,0,[0, 1, 2]] = (15, 16, 17)
print(arr3D)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 


[[[15 16 17]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
