## Broadcasting in NumPy
Now, we'll explore how to make your code faster with vectorization and broadcasting in NumPy. These techniques are key to boosting performance in numerical operations by avoiding slow loops and memory inefficiency.

In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [8]:
result = arr ** 2  # Vectorized operation
print(result)

[ 1  4  9 16 25 36]


In [9]:
print(result + 10) # Broadcasting: 10 is added to all elements

[11 14 19 26 35 46]


In [11]:
#Broadcasting with Arrays of Different Shapes

#In normal list
arr_1 = [1, 2, 3]
arr_2 = [10, 11, 12]
print(arr_1 + arr_2)

arr_1 = np.array([1, 2, 3])
arr_1 = np.array([10, 11, 12])
print(arr_1 + arr_2)

[1, 2, 3, 10, 11, 12]
[20 22 24]


In [12]:
arr_1 = np.array([[1, 2, 3], [10, 11, 12]])
arr_2 = np.array([1, 2, 3])
print(arr_1 + arr_2)

[[ 2  4  6]
 [11 13 15]]


In [13]:
arr_1 = np.array([[1, 2, 3], [10, 11, 12]])
arr_2 = np.array([[1, 2, 3], [10, 11, 12]])
print(arr_1 + arr_2)

[[ 2  4  6]
 [20 22 24]]


In [15]:
#Z-score Standardization
data = np.array([[10, 20, 30],
                [15, 25, 35],
                [20, 30, 40],
                [25, 35, 45],
                [30, 40, 50]])
data_mean = data.mean(axis = 0)
data_standard = data.std(axis = 0)

normalized_data = (data - data_mean)/data_standard
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
