## Built in Mathematical Functions in NumPy
Here are some common NumPy methods that are frequently used for statistical and mathematical operations:

1. np.mean() – Compute the mean (average) of an array.
np.mean(arr)

2. np.std() – Compute the standard deviation of an array.
np.std(arr)

3. np.var() – Compute the variance of an array.
np.var(arr)

4. np.min() – Compute the minimum value of an array.
np.min(arr)

5. np.max() – Compute the maximum value of an array.
np.max(arr)

6. np.sum() – Compute the sum of all elements in an array.
np.sum(arr)

7. np.prod() – Compute the product of all elements in an array.
np.prod(arr)

8. np.median() – Compute the median of an array.
np.median(arr)

9. np.percentile() – Compute the percentile of an array.
np.percentile(arr, 50)  # For the 50th percentile (median)

10. np.argmin() – Return the index of the minimum value in an array.
np.argmin(arr)

11. np.argmax() – Return the index of the maximum value in an array.
np.argmax(arr)

12. np.corrcoef() – Compute the correlation coefficient matrix of two arrays.
np.corrcoef(arr1, arr2)

13. np.unique() – Find the unique elements of an array.
np.unique(arr)

14. np.diff() – Compute the n-th differences of an array.
np.diff(arr)

15. np.cumsum() – Compute the cumulative sum of an array.
np.cumsum(arr)

16. np.linspace() – Create an array with evenly spaced numbers over a specified interval.
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

17. np.log() – Compute the natural logarithm of an array.
np.log(arr)

18. np.exp() – Compute the exponential of an array.
np.exp(arr)

These methods are used for performing mathematical and statistical operations with NumPy

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [2]:
print(np.mean(arr))

40.0


In [3]:
print(np.min(arr))

10


In [4]:
print(np.max(arr))

70


In [5]:
print(np.std(arr))

20.0


In [12]:
print(np.var(arr))

400.0


In [6]:
print(np.sum(arr))

280


In [7]:
print(np.prod(arr))

50400000000


In [8]:
print(np.median(arr))

40.0


In [14]:
print(np.percentile(arr, 50))

40.0


In [15]:
print(np.argmin(arr))

0


In [16]:
print(np.argmax(arr))

6


In [20]:
arr_2 = np.array([11, 22, 33, 44, 55, 66, 77])
print(np.corrcoef(arr, arr_2))

[[1. 1.]
 [1. 1.]]


In [23]:
arr_3 = np.array([1, 5, 4, 9, 32, 5, 2, 1, 9, 2, 11, 7, 13])
print(np.unique(arr_3))

[ 1  2  4  5  7  9 11 13 32]


In [24]:
print(np.diff(arr))

[10 10 10 10 10 10]


In [25]:
print(np.cumsum(arr))

[ 10  30  60 100 150 210 280]


In [29]:
print(np.linspace(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]


In [30]:
print(np.log(arr))

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301 4.09434456
 4.24849524]


In [31]:
print(np.exp(arr))

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21 1.14200739e+26 2.51543867e+30]
