# Exercises for Practice
1. Create a 3×3 array filled with random numbers and print its shape.
2. Convert an array of floats [1.1, 2.2, 3.3] into integers.
3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
4. Reshape a 1D array of size 9 into a 3×3 matrix.
5. Use boolean masking to filter numbers greater than 50 in an array.


In [1]:
import numpy as np

In [4]:
#1

arr = np.full((3, 3), 7)
print(arr)
print(arr.shape)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
(3, 3)


In [5]:
#2

arr = np.array([1.1, 2.2, 3.3])
arr = arr.astype('int64')
print(arr, arr.dtype)

[1 2 3] int64


In [13]:
#3
#using fancy indexing
arr = np.array([1, 2, 3, 4, 5, 6])
index = [1, 3, 5]
print(arr[index])

#using masking
print(arr[arr%2==0])

[2 4 6]
[2 4 6]


In [10]:
#4

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr = np.array([range(101)])
print(arr)
greater_than_50 = arr[arr>50].copy()
print(greater_than_50)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
   54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
   72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
   90  91  92  93  94  95  96  97  98  99 100]]
[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
